#!/bin/bash

snakemake --latency-wait 100 --cluster-config cluster_wildcard.yaml --cluster "sbatch --parsable -J '{cluster.name}' -p {cluster.partition} -n 1 --cpus-per-task {threads} --time=4-00:00:00 -o '{cluster.output}' --mem {resources.mem_mb}" "$@"
